import type { ignoreOptions } from '../types/ignore.js'
import { writeFileSync, existsSync } from 'fs'
import { log } from '@clack/prompts'
import handleError from '../tools/handleError.js'
import path from 'path'

class glcIgnoreManager {
    private verbose: boolean = false

    public async run(options: ignoreOptions) {
        this.verbose = options.verbose ?? false

        const template = options.template ?? this.getTemplateName()
        await this.applyTemplate(template)
    }

    private getTemplateName(): string {
        // Default to Node.js template if no template specified
        return 'node'
    }

    private async applyTemplate(templateName: string) {
        try {
            const gitignoreContent = this.getTemplateContent(templateName)
            const gitignorePath = path.join(process.cwd(), '.gitignore')

            if (existsSync(gitignorePath)) {
                log.warn(
                    '.gitignore file already exists. Backing up the existing file...'
                )
                const backupPath = `${gitignorePath}.backup.${Date.now()}`
                const existingContent = require('fs').readFileSync(
                    gitignorePath,
                    'utf-8'
                )
                writeFileSync(backupPath, existingContent)
                log.info(`Backup created: ${backupPath}`)
            }

            writeFileSync(gitignorePath, gitignoreContent)

            if (this.verbose) {
                log.success(
                    `Generated .gitignore file with ${templateName} template`
                )
            }
        } catch (error) {
            handleError(error, this.verbose)
        }
    }

    private getTemplateContent(templateName: string): string {
        const templates = {
            node: this.getNodeTemplate(),
            python: this.getPythonTemplate(),
            typescript: this.getTypescriptTemplate(),
            generic: this.getGenericTemplate(),
        }

        return (
            templates[templateName as keyof typeof templates] ||
            templates.generic
        )
    }

    private getNodeTemplate(): string {
        return `# Node.js dependencies
node_modules/

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage/

# Dependency directories
jspm_packages/

# Optional npm cache directory
.npm

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db`
    }

    private getPythonTemplate(): string {
        return `# Python
__pycache__/
*.py[cod]
*$py.class

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# PyInstaller
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/
.pytest_cache/

# Virtual environments
venv/
env/
ENV/

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db`
    }

    private getTypescriptTemplate(): string {
        return `# Dependencies
node_modules/

# Compiled output
/dist/
/build/
*.js
*.js.map
*.d.ts

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Coverage directory used by tools like istanbul
coverage/

# Dependency directories
jspm_packages/

# Optional npm cache directory
.npm

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db`
    }

    private getGenericTemplate(): string {
        return `# Dependencies
node_modules/

# Build output
dist/
build/

# Logs
*.log

# Environment variables
.env

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db`
    }
}
export default glcIgnoreManager
